[2022-10-13T09:07:52.593+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: testing_pipeline.Preprocess scheduled__2022-08-25T00:00:00+00:00 [queued]>
[2022-10-13T09:07:52.606+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: testing_pipeline.Preprocess scheduled__2022-08-25T00:00:00+00:00 [queued]>
[2022-10-13T09:07:52.606+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-13T09:07:52.607+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-13T09:07:52.607+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-13T09:07:52.628+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): Preprocess> on 2022-08-25 00:00:00+00:00
[2022-10-13T09:07:52.632+0000] {standard_task_runner.py:54} INFO - Started process 10984 to run task
[2022-10-13T09:07:52.635+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'testing_pipeline', 'Preprocess', 'scheduled__2022-08-25T00:00:00+00:00', '--job-id', '809', '--raw', '--subdir', 'DAGS_FOLDER/test_pipeline.py', '--cfg-path', '/tmp/tmpxn4nj8ge']
[2022-10-13T09:07:52.636+0000] {standard_task_runner.py:83} INFO - Job 809: Subtask Preprocess
[2022-10-13T09:07:52.637+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/test_pipeline.py
[2022-10-13T09:07:55.147+0000] {task_command.py:384} INFO - Running <TaskInstance: testing_pipeline.Preprocess scheduled__2022-08-25T00:00:00+00:00 [running]> on host d013b488c150
[2022-10-13T09:07:55.210+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=protik.nag
AIRFLOW_CTX_DAG_ID=testing_pipeline
AIRFLOW_CTX_TASK_ID=Preprocess
AIRFLOW_CTX_EXECUTION_DATE=2022-08-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-25T00:00:00+00:00
[2022-10-13T09:07:55.213+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/preprocess.py", line 37, in preprocess
    target_size=(150, 150)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/image.py", line 1668, in flow_from_directory
    dtype=self.dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [Errno 2] No such file or directory: '../data/train/'
[2022-10-13T09:07:55.220+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=testing_pipeline, task_id=Preprocess, execution_date=20220825T000000, start_date=20221013T090752, end_date=20221013T090755
[2022-10-13T09:07:55.232+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 809 for task Preprocess ([Errno 2] No such file or directory: '../data/train/'; 10984)
[2022-10-13T09:07:55.261+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-13T09:07:55.284+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
