[2022-10-13T09:07:12.520+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: testing_pipeline.Preprocess scheduled__2022-06-12T00:00:00+00:00 [queued]>
[2022-10-13T09:07:12.529+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: testing_pipeline.Preprocess scheduled__2022-06-12T00:00:00+00:00 [queued]>
[2022-10-13T09:07:12.530+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-13T09:07:12.530+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-13T09:07:12.530+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-13T09:07:12.545+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): Preprocess> on 2022-06-12 00:00:00+00:00
[2022-10-13T09:07:12.549+0000] {standard_task_runner.py:54} INFO - Started process 10727 to run task
[2022-10-13T09:07:12.550+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'testing_pipeline', 'Preprocess', 'scheduled__2022-06-12T00:00:00+00:00', '--job-id', '735', '--raw', '--subdir', 'DAGS_FOLDER/test_pipeline.py', '--cfg-path', '/tmp/tmp4ma167_l']
[2022-10-13T09:07:12.551+0000] {standard_task_runner.py:83} INFO - Job 735: Subtask Preprocess
[2022-10-13T09:07:12.552+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/test_pipeline.py
[2022-10-13T09:07:14.795+0000] {task_command.py:384} INFO - Running <TaskInstance: testing_pipeline.Preprocess scheduled__2022-06-12T00:00:00+00:00 [running]> on host d013b488c150
[2022-10-13T09:07:14.953+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=protik.nag
AIRFLOW_CTX_DAG_ID=testing_pipeline
AIRFLOW_CTX_TASK_ID=Preprocess
AIRFLOW_CTX_EXECUTION_DATE=2022-06-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-12T00:00:00+00:00
[2022-10-13T09:07:14.956+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/preprocess.py", line 37, in preprocess
    target_size=(150, 150)
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/image.py", line 1668, in flow_from_directory
    dtype=self.dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/preprocessing/image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [Errno 2] No such file or directory: '../data/train/'
[2022-10-13T09:07:14.982+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=testing_pipeline, task_id=Preprocess, execution_date=20220612T000000, start_date=20221013T090712, end_date=20221013T090714
[2022-10-13T09:07:15.006+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 735 for task Preprocess ([Errno 2] No such file or directory: '../data/train/'; 10727)
[2022-10-13T09:07:15.053+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-13T09:07:15.105+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
